<?xml version="1.0" encoding="utf-8"?><Database Name="fb" Class="dbtestDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=XPANDER\SQLEXPRESS;Initial Catalog=fb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="fbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Orders" Member="Orders">
    <Type Name="Orders">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="merch" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ProstoNames1_Orders1" Member="ProstoNames" ThisKey="name_id" OtherKey="Id" Type="ProstoNames" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProstoNames" Member="ProstoNames">
    <Type Name="ProstoNames">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="ProstoNames1_Orders1" Member="Orders" ThisKey="Id" OtherKey="name_id" Type="Orders" />
    </Type>
  </Table>
</Database>